# Generated by Django 5.2.7 on 2025-11-16 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_marks'),
        ('teacher', '0004_remove_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='student.student'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='teacher.subject'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_marks', to='teacher.teacher'),
        ),
    ]
