# Generated by Django 5.2.7 on 2025-12-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_teacher'),
        ('teacher', '0006_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('weak_topics', models.CharField(blank=True, max_length=255)),
                ('question_paper_image', models.ImageField(blank=True, null=True, upload_to='improvement_plans/question_papers/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_plans', to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_plans', to='teacher.teacher')),
            ],
        ),
    ]
