# Generated by Django 5.2.7 on 2025-10-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='remarks',
        ),
        migrations.AddField(
            model_name='fee',
            name='month',
            field=models.CharField(default='January', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
