# Generated by Django 5.2.7 on 2025-10-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='mesage',
            new_name='message',
        ),
    ]
