# Generated by Django 5.2.7 on 2025-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
