# Generated by Django 5.2.7 on 2025-11-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.parent'),
        ),
    ]
