# Generated by Django 5.2.7 on 2025-11-25 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
        ('student', '0006_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistnote',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_notes', to='student.student'),
        ),
    ]
