# Generated by Django 5.2.7 on 2025-12-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_receptionistnote_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='note_access',
            field=models.BooleanField(default=True),
        ),
    ]
